language: node_js
node_js:
  - '8'
  - '6'
email:
  recipients:
    - ngyv.codes@gmail.com
after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
